x-plugin:
  &plugin-common # image: registry.gitlab.com/slurpit.io/slurpit-netbox-docker:latest
  build: .
  networks:
    - slurpit-network

x-api: &api_common
  environment:
    # ALLOWED_ORIGINS: '["*"]' # CORS domains
    # API_URL: http://api:8000  # backend-endpoint with respect to service name and exposed port
    # AUTH_BACKEND: netyce_alchemy  # auhenticating/authorizing backend
    # BEAT_DB_URI: "postgresql+psycopg2://netpicker:netpicker@db/netpicker"  # Celery Beat Pg connection string
    # DB_URI: "postgresql+asyncpg://netpicker:netpicker@db/netpicker"  # Async Pg connection string (API)
    CELERY_BROKER_URL: redis://netpicker-redis
    CELERY_RESULT_BACKEND: redis://netpicker-redis
    # CLI_PROXY_HOST: agent
    # ENABLE_AUDIT_LOGGING: 1 # Enables audit logging for user actions in the API including POST body content
    # GIT_REPO_MANAGER: '["gitd",9419]'
    # GIT_SERVER: git://gitd
    # INIT_USER: 'admin@admin.com'
    # INIT_PASSWORD: '12345678'
    # INIT_TENANT: 'default'
    # JWT_AUDIENCE: "netpicker"
    # JWT_ALGORITHM: HS256
    # JWT_SECRET: ew9023cnkljfcnsdlkfsfdhs
    # NETBOX_API: "https://netbox-endpoint/"
    # NETBOX_TOKEN: netbox_token_here
    # PROXY_SSL_VERIFY: 0 # Do not verify any SSL certificate
    # PROXY_SSL_VERIFY_EXEMPT_HOST: '["my.host", "your.host"]' # Do not verify SSL certificates for given hostnames
    # PUBLIC_POLICIES:
    REDIS_URL: redis://netpicker-redis
    # RUN_TESTS_ON_CONFIG_CHANGE: 0 # Don't automatically run the rules when the config of a device has changed
    # SLURPIT_APIKEY: slurpit_apikey_here
    # SLURPIT_URL: "https://slurpit-endpoint/"
    # WORKDIR_VOLUME_PATH: /data/policy-workdir
    # CVE_LIST_V5_REPO_URI: 'https://github.com/CVEProject/cvelistv5.git'

services:
  slurpit-warehouse:
    image: slurpit/warehouse:dev
    environment:
      TZ: Europe/Amsterdam
      WAREHOUSE_PORTAL_URL: http://slurpit-portal

  slurpit-scraper:
    image: slurpit/scraper:dev
    environment:
      TZ: Europe/Amsterdam
      SCRAPER_TIMEOUT: 20
      SCRAPER_POOLSIZE: 32
      SCRAPER_WAREHOUSE_HOSTNAME: slurpit-warehouse

  slurpit-scanner:
    image: slurpit/scanner:dev
    environment:
      TZ: Europe/Amsterdam
      SCANNER_POOLSIZE: 32
      SCANNER_SNMP_TIMEOUT: 6
      # https://slurpit.io/knowledge-base/fine-tune-the-device-finder
      # SCANNER_ICMP_ENABLED: false
      # SCANNER_ARP_ENABLED: false
      # SCANNER_TCP_ENABLED: true
      # SCANNER_TCP_PORTS: "[22,23]"
      SCANNER_WAREHOUSE_HOSTNAME: slurpit-warehouse

  slurpit-portal:
    image: slurpit/portal:dev
    environment:
      TZ: Europe/Amsterdam
      PORTAL_BASE_URL: http://localhost
      PORTAL_WAREHOUSE_URL: http://slurpit-warehouse
      PORTAL_MENU_MODE: "shortcuts"
      PORTAL_NETPICKER_URL: "https://netpicker.io"
    ports:
      - "80:80"
      - "443:443"
  netbox:
    container_name: slurpit-netbox-app
    <<: *plugin-common
    ports:
      - 8080:8080
  netbox-worker:
    <<: *plugin-common
  netbox-housekeeping:
    <<: *plugin-common
  postgres:
    ports:
      - 5432:5432

  # Netpicker service overrides
  netpicker-api:
    <<: *api_common

  netpicker-celery:
    <<: *api_common

  #netpicker-gitd:
  #environment:
  # EXTERNAL_GIT_MAPPINGS: '{"rules/default.git": "https://github.com/netpicker/rules-default.git", "configs/default.git": "https://github.com/netpicker/configs-default.git"}'
  # EXTERNAL_GIT_TOKEN: "github_pat_abc"
  # EXTERNAL_GIT_USERNAME: "netpicker"

  #netpicker-agent:
  #environment:
  # CLI_TRACE_DIR: /tmp/trace-cli
  # DEDICATED_CONNECTIONS: 1
  # SHENV_JUMP_HOST: '192.168.x.x'  # target address of file transfer via scp/sftp/ftp/tftp
